version: '3.8'

networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net


  httpd-1:
    image: httpd
    volumes:
      - ./httpd-1:/usr/local/apache2/htdocs
    ports:
      - 8081:80
    networks:
      - nginx_net

  httpd-2:
    image: httpd
    volumes:
      - ./httpd-2:/usr/local/apache2/htdocs
    ports:
      - 8082:80
    networks:
      - nginx_net


  httpd-host:
    image: httpd
    volumes:
      - ./httpd-host:/usr/local/apache2/htdocs
    ports:
      - 8083:80
    networks:
      - nginx_net
